app:
  defaultName: World
spring:
  application:
    name: hello-world
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}