apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-hello-world
  namespace: openshift-gitops
spec:
  destination:
    namespace: hello-world
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: environments/prod
    repoURL: 'https://github.com/cmays20/hello-world-deploy.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
